apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  # namespace: dev # specifing namespace - not required
  labels: 
    app: myapp
    type: front-end
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
