apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  # namespace: dev # specifing namespace - not required
  labels: 
    app: myapp
    type: front-end
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: Exists

            # affinities 
            # requiredDuringSchedulingIgnoredDuringExecution
            # preferredDuringSchedulingIgnoredDuringExecution
            # requiredDuringSchedulingRequiredDuringExecution